# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Windows-latest'
  #name: Default
steps:


- task: AndroidSigning@3
  inputs:
    apkFiles: 'app-debug.apk'
    apksignerKeystoreFile: 'awwal'
    apksignerKeystorePassword: 'password'
    zipalign: false
    apksignerKeystoreAlias: 'hafsa'

- task: AndroidSigningm@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'awwal'
    apksignerKeystorePassword: 'password'
    apksignerKeystoreAlias: 'hafsa'
    zipalign: false
    apksignerVersion: 'latest'
