# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'
  #name: Default
steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir 'test'
      touch $(Build.ArtifactStagingDirectory)/test.txt

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadBuildArtifactsm@0
  inputs:
    buildType: 'specific'
    project: '796fd84e-1ff6-498a-a8c1-5fe857957c21'
    pipeline: '9'
    buildVersionToDownload: 'specific'
    buildId: '1471'
    downloadType: 'specific'
    itemPattern: '*/test.txt'
    downloadPath: '$(System.ArtifactsDirectory)'
    checkDownloadedFiles: true

#- task: AndroidSigningm@2
 # inputs:
 #   apkFiles: 'app-debug.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   zipalign: false
 #   jarsignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@2
 # inputs:
 #   apkFiles: '**/*.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   jarsignerKeystoreAlias: 'hafsa'
 #   zipalign: false

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: 'app-debug.apk'
#    apksignerKeystoreFile: 'awwal'
#    apksignerKeystorePassword: 'password'
#    zipalign: false
#    apksignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: '**/*.apk'
#    apksignerKeystoreFile: 'awwal'
 #   apksignerKeystorePassword: 'password'
#    apksignerKeystoreAlias: 'hafsa'
#    zipalign: false
#    apksignerVersion: 'latest'
