# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Ubuntu-latest'
  name: Default
steps:

#- task: Gradle@2
#  inputs:
#    gradleWrapperFile: 'C:\agent\_work\3\s\.git\HEAD'
#    workingDirectory: '$(Build.SourcesDirectory)/android'
#    tasks: 'build'
#    publishJUnitResults: true
#    testResultsFiles: '**/TEST-*.xml'
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: false


#- task: AndroidSigning@3
#  inputs:
#    apkFiles: 'app-debug.apk'
##    apksignerKeystoreFile: 'awwal'
##    apksignerKeystorePassword: 'password'
 #   zipalign: false
 #   apksignerKeystoreAlias: 'hafsa'

- task: AndroidSigningm@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'awwal'
    apksignerKeystorePassword: 'password'
    apksignerKeystoreAlias: 'hafsa'
    zipalign: false
    apksignerVersion: 'latest'
   