# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Windows-latest'
  name: Default

steps:
- script: |
    mkdir 'test'
    echo 'erer' > $(Build.ArtifactStagingDirectory)/test.txt


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host '##vso[artifact.upload
      artifactname=test;
      containerfolder=Staging;
      artifacttype=container;
      localpath=$(Build.ArtifactStagingDirectory)/test.txt
      ]$(Build.ArtifactStagingDirectory)/test.txt'

#- task: AndroidSigningm@2
 # inputs:
 #   apkFiles: 'app-debug.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   zipalign: false
 #   jarsignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@2
 # inputs:
 #   apkFiles: '**/*.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   jarsignerKeystoreAlias: 'hafsa'
 #   zipalign: false

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: 'app-debug.apk'
#    apksignerKeystoreFile: 'awwal'
#    apksignerKeystorePassword: 'password'
#    zipalign: false
#    apksignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: '**/*.apk'
#    apksignerKeystoreFile: 'awwal'
 #   apksignerKeystorePassword: 'password'
#    apksignerKeystoreAlias: 'hafsa'
#    zipalign: false
#    apksignerVersion: 'latest'
