# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'Windows-latest'
  name: Default

steps:

- powershell: |
    New-Item -ItemType file testFile.xml

- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    Contents: 'testFile.xml'
    TargetFolder: '\\fs\Public\egor.bryzgalov\test'
    CleanTargetFolder: true
    OverWrite: true


# artifactname=test
#- task: AndroidSigningm@2
 # inputs
 #   apkFiles: 'app-debug.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   zipalign: false
 #   jarsignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@2
 # inputs:
 #   apkFiles: '**/*.apk'
 #   jarsignerKeystoreFile: 'awwal'
 #   jarsignerKeystorePassword: 'password'
 #   jarsignerKeystoreAlias: 'hafsa'
 #   zipalign: false

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: 'app-debug.apk'
#    apksignerKeystoreFile: 'awwal'
#    apksignerKeystorePassword: 'password'
#    zipalign: false
#    apksignerKeystoreAlias: 'hafsa'

#- task: AndroidSigningm@3
#  inputs:
#    apkFiles: '**/*.apk'
#    apksignerKeystoreFile: 'awwal'
 #   apksignerKeystorePassword: 'password'
#    apksignerKeystoreAlias: 'hafsa'
#    zipalign: false
#    apksignerVersion: 'latest'
